return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        "templ",
        "go",
        "gomod",
        "gowork",
        "gosum",
        "html",
        "php",
        "javascript",
        "css",
        "svelte",
        "typescript",
        "tsx",
        "json",
        "yaml",
        "markdown",
        "markdown_inline",
        "fish",
        "fish_indent",
        "dockerfile",
        "docker_compose",
      },
    },
  },
}
